"""
FBX Exporter Module
===================

Exports hair strands as Maya-compatible FBX curves.
This module generates NURBS curves that can be directly imported into Maya
and used with hair simulation systems like XGen or nHair.
"""

import struct
import numpy as np
from typing import Optional, List, Dict, Any
from dataclasses import dataclass
from pathlib import Path
import time

# Import hair strands types
from src.core.hair_strands import HairStrand, HairStrandCollection


@dataclass
class FBXExportOptions:
    """Options for FBX export."""
    curve_type: str = "nurbs"  # "nurbs" or "bezier"
    up_axis: str = "Y"  # "Y" or "Z"
    scale_factor: float = 1.0
    include_color: bool = True
    include_width: bool = True
    group_name: str = "HairCurves"
    maya_compatible: bool = True
    binary_format: bool = False  # ASCII is more compatible


class FBXExporter:
    """
    Exports hair strands to Maya-compatible FBX format.
    
    Creates NURBS curves that can be used directly in Maya for:
    - Hair rendering
    - Hair simulation (nHair)
    - XGen hair systems
    - Arnold/RenderMan hair primitives
    """
    
    def __init__(self, options: Optional[FBXExportOptions] = None):
        """
        Initialize the FBX exporter.
        
        Args:
            options: Export options
        """
        self.options = options or FBXExportOptions()
        self._node_id_counter = 0
        
    def export(
        self,
        strands: HairStrandCollection,
        output_path: str,
        callback: Optional[callable] = None
    ) -> bool:
        """
        Export strands to FBX file.
        
        Args:
            strands: Hair strand collection to export
            output_path: Output file path
            callback: Progress callback function
            
        Returns:
            True if export succeeded
        """
        try:
            if callback:
                callback(0.1, "Preparing data...")
            
            # Generate FBX content
            fbx_content = self._generate_fbx_ascii(strands, callback)
            
            if callback:
                callback(0.9, "Writing file...")
            
            # Write to file
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(fbx_content)
            
            if callback:
                callback(1.0, "Export complete!")
            
            return True
            
        except Exception as e:
            print(f"FBX export error: {e}")
            return False
    
    def _generate_fbx_ascii(
        self,
        strands: HairStrandCollection,
        callback: Optional[callable] = None
    ) -> str:
        """Generate FBX ASCII format content."""
        self._node_id_counter = 0
        
        lines = []
        
        # FBX Header
        lines.extend(self._generate_header())
        
        # Global Settings
        lines.extend(self._generate_global_settings())
        
        # Documents
        lines.extend(self._generate_documents())
        
        # References
        lines.extend(self._generate_references())
        
        # Definitions
        lines.extend(self._generate_definitions(strands.num_strands))
        
        # Objects (Curves)
        if callback:
            callback(0.3, "Generating curves...")
        lines.extend(self._generate_objects(strands, callback))
        
        # Connections
        if callback:
            callback(0.8, "Building connections...")
        lines.extend(self._generate_connections(strands))
        
        # Takes
        lines.extend(self._generate_takes())
        
        return '\n'.join(lines)
    
    def _get_next_id(self) -> int:
        """Get next unique node ID."""
        self._node_id_counter += 1
        return 1000000000 + self._node_id_counter
    
    def _generate_header(self) -> List[str]:
        """Generate FBX header section."""
        timestamp = time.strftime("%Y/%m/%d %H:%M:%S")
        
        return [
            "; FBX 7.7.0 project file",
            "; Generated by GaussianHairCube",
            "; ----------------------------------------------------",
            "",
            "FBXHeaderExtension:  {",
            "\tFBXHeaderVersion: 1004",
            "\tFBXVersion: 7700",
            "\tCreationTimeStamp:  {",
            "\t\tVersion: 1000",
            f"\t\tYear: {time.localtime().tm_year}",
            f"\t\tMonth: {time.localtime().tm_mon}",
            f"\t\tDay: {time.localtime().tm_mday}",
            f"\t\tHour: {time.localtime().tm_hour}",
            f"\t\tMinute: {time.localtime().tm_min}",
            f"\t\tSecond: {time.localtime().tm_sec}",
            "\t\tMillisecond: 0",
            "\t}",
            '\tCreator: "GaussianHairCube 1.0.0"',
            "\tOtherFlags:  {",
            "\t\tFlagPLE: 0",
            "\t}",
            "}",
            "",
        ]
    
    def _generate_global_settings(self) -> List[str]:
        """Generate global settings section."""
        up_axis = 1 if self.options.up_axis == "Y" else 2
        up_sign = 1
        front_axis = 2 if self.options.up_axis == "Y" else 1
        front_sign = 1
        
        return [
            "GlobalSettings:  {",
            "\tVersion: 1000",
            "\tProperties70:  {",
            "\t\tP: \"UpAxis\", \"int\", \"Integer\", \"\"," + str(up_axis),
            "\t\tP: \"UpAxisSign\", \"int\", \"Integer\", \"\"," + str(up_sign),
            "\t\tP: \"FrontAxis\", \"int\", \"Integer\", \"\"," + str(front_axis),
            "\t\tP: \"FrontAxisSign\", \"int\", \"Integer\", \"\"," + str(front_sign),
            "\t\tP: \"CoordAxis\", \"int\", \"Integer\", \"\",0",
            "\t\tP: \"CoordAxisSign\", \"int\", \"Integer\", \"\",1",
            "\t\tP: \"OriginalUpAxis\", \"int\", \"Integer\", \"\"," + str(up_axis),
            "\t\tP: \"OriginalUpAxisSign\", \"int\", \"Integer\", \"\",1",
            f"\t\tP: \"UnitScaleFactor\", \"double\", \"Number\", \"\",{self.options.scale_factor}",
            f"\t\tP: \"OriginalUnitScaleFactor\", \"double\", \"Number\", \"\",{self.options.scale_factor}",
            "\t\tP: \"AmbientColor\", \"ColorRGB\", \"Color\", \"\",0,0,0",
            "\t\tP: \"DefaultCamera\", \"KString\", \"\", \"\", \"Producer Perspective\"",
            "\t\tP: \"TimeMode\", \"enum\", \"\", \"\",6",
            "\t\tP: \"TimeProtocol\", \"enum\", \"\", \"\",2",
            "\t\tP: \"SnapOnFrameMode\", \"enum\", \"\", \"\",0",
            "\t\tP: \"TimeSpanStart\", \"KTime\", \"Time\", \"\",0",
            "\t\tP: \"TimeSpanStop\", \"KTime\", \"Time\", \"\",153953860000",
            "\t\tP: \"CustomFrameRate\", \"double\", \"Number\", \"\",-1",
            "\t}",
            "}",
            "",
        ]
    
    def _generate_documents(self) -> List[str]:
        """Generate documents section."""
        return [
            "Documents:  {",
            "\tCount: 1",
            "\tDocument: 1000000000, \"\", \"Scene\" {",
            "\t\tProperties70:  {",
            "\t\t\tP: \"SourceObject\", \"object\", \"\", \"\"",
            "\t\t\tP: \"ActiveAnimStackName\", \"KString\", \"\", \"\", \"Take 001\"",
            "\t\t}",
            "\t\tRootNode: 0",
            "\t}",
            "}",
            "",
        ]
    
    def _generate_references(self) -> List[str]:
        """Generate references section."""
        return [
            "References:  {",
            "}",
            "",
        ]
    
    def _generate_definitions(self, num_curves: int) -> List[str]:
        """Generate definitions section."""
        return [
            "Definitions:  {",
            "\tVersion: 100",
            f"\tCount: {3 + num_curves}",  # GlobalSettings + Model(Null) + Model(Curves) + Geometries
            "\tObjectType: \"GlobalSettings\" {",
            "\t\tCount: 1",
            "\t}",
            "\tObjectType: \"Model\" {",
            f"\t\tCount: {1 + num_curves}",  # Root + curves
            "\t\tPropertyTemplate: \"FbxNode\" {",
            "\t\t\tProperties70:  {",
            "\t\t\t\tP: \"QuaternionInterpolate\", \"enum\", \"\", \"\",0",
            "\t\t\t\tP: \"RotationOffset\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"RotationPivot\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"ScalingOffset\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"ScalingPivot\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"TranslationActive\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"TranslationMin\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"TranslationMax\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"TranslationMinX\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"TranslationMinY\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"TranslationMinZ\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"TranslationMaxX\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"TranslationMaxY\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"TranslationMaxZ\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"RotationOrder\", \"enum\", \"\", \"\",0",
            "\t\t\t\tP: \"RotationSpaceForLimitOnly\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"RotationStiffnessX\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"RotationStiffnessY\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"RotationStiffnessZ\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"AxisLen\", \"double\", \"Number\", \"\",10",
            "\t\t\t\tP: \"PreRotation\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"PostRotation\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"RotationActive\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"RotationMin\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"RotationMax\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"RotationMinX\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"RotationMinY\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"RotationMinZ\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"RotationMaxX\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"RotationMaxY\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"RotationMaxZ\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"InheritType\", \"enum\", \"\", \"\",0",
            "\t\t\t\tP: \"ScalingActive\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"ScalingMin\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"ScalingMax\", \"Vector3D\", \"Vector\", \"\",1,1,1",
            "\t\t\t\tP: \"ScalingMinX\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"ScalingMinY\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"ScalingMinZ\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"ScalingMaxX\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"ScalingMaxY\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"ScalingMaxZ\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"GeometricTranslation\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"GeometricRotation\", \"Vector3D\", \"Vector\", \"\",0,0,0",
            "\t\t\t\tP: \"GeometricScaling\", \"Vector3D\", \"Vector\", \"\",1,1,1",
            "\t\t\t\tP: \"MinDampRangeX\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"MinDampRangeY\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"MinDampRangeZ\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"MaxDampRangeX\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"MaxDampRangeY\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"MaxDampRangeZ\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"MinDampStrengthX\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"MinDampStrengthY\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"MinDampStrengthZ\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"MaxDampStrengthX\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"MaxDampStrengthY\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"MaxDampStrengthZ\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"PreferedAngleX\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"PreferedAngleY\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"PreferedAngleZ\", \"double\", \"Number\", \"\",0",
            "\t\t\t\tP: \"LookAtProperty\", \"object\", \"\", \"\"",
            "\t\t\t\tP: \"UpVectorProperty\", \"object\", \"\", \"\"",
            "\t\t\t\tP: \"Show\", \"bool\", \"\", \"\",1",
            "\t\t\t\tP: \"NegativePercentShapeSupport\", \"bool\", \"\", \"\",1",
            "\t\t\t\tP: \"DefaultAttributeIndex\", \"int\", \"Integer\", \"\",-1",
            "\t\t\t\tP: \"Freeze\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"LODBox\", \"bool\", \"\", \"\",0",
            "\t\t\t\tP: \"Lcl Translation\", \"Lcl Translation\", \"\", \"A\",0,0,0",
            "\t\t\t\tP: \"Lcl Rotation\", \"Lcl Rotation\", \"\", \"A\",0,0,0",
            "\t\t\t\tP: \"Lcl Scaling\", \"Lcl Scaling\", \"\", \"A\",1,1,1",
            "\t\t\t\tP: \"Visibility\", \"Visibility\", \"\", \"A\",1",
            "\t\t\t\tP: \"Visibility Inheritance\", \"Visibility Inheritance\", \"\", \"\",1",
            "\t\t\t}",
            "\t\t}",
            "\t}",
            "\tObjectType: \"Geometry\" {",
            f"\t\tCount: {num_curves}",
            "\t\tPropertyTemplate: \"FbxNurbsCurve\" {",
            "\t\t\tProperties70:  {",
            "\t\t\t\tP: \"Color\", \"ColorRGB\", \"Color\", \"\",0.8,0.8,0.8",
            "\t\t\t}",
            "\t\t}",
            "\t}",
            "}",
            "",
        ]
    
    def _generate_objects(
        self,
        strands: HairStrandCollection,
        callback: Optional[callable] = None
    ) -> List[str]:
        """Generate objects section with curves."""
        lines = ["Objects:  {"]
        
        # Root null node
        root_id = self._get_next_id()
        self._root_id = root_id
        
        lines.extend([
            f'\tModel: {root_id}, "Model::{self.options.group_name}", "Null" {{',
            "\t\tVersion: 232",
            "\t\tProperties70:  {",
            "\t\t\tP: \"Lcl Translation\", \"Lcl Translation\", \"\", \"A\",0,0,0",
            "\t\t\tP: \"Lcl Rotation\", \"Lcl Rotation\", \"\", \"A\",0,0,0",
            "\t\t\tP: \"Lcl Scaling\", \"Lcl Scaling\", \"\", \"A\",1,1,1",
            "\t\t}",
            "\t\tShading: Y",
            "\t\tCulling: \"CullingOff\"",
            "\t}",
        ])
        
        # Store curve IDs for connections
        self._curve_model_ids = []
        self._curve_geometry_ids = []
        
        # Generate each curve
        num_strands = strands.num_strands
        for i, strand in enumerate(strands.strands):
            if callback and i % 100 == 0:
                progress = 0.3 + 0.5 * (i / num_strands)
                callback(progress, f"Generating curve {i}/{num_strands}")
            
            curve_lines = self._generate_curve(strand, i)
            lines.extend(curve_lines)
        
        lines.append("}")
        lines.append("")
        
        return lines
    
    def _generate_curve(self, strand: HairStrand, index: int) -> List[str]:
        """Generate a single NURBS curve."""
        lines = []
        
        # Curve model node
        model_id = self._get_next_id()
        geometry_id = self._get_next_id()
        
        self._curve_model_ids.append(model_id)
        self._curve_geometry_ids.append(geometry_id)
        
        curve_name = f"HairCurve_{index:05d}"
        
        # Scale points
        points = strand.points * self.options.scale_factor
        
        # Convert coordinate system if needed
        if self.options.up_axis == "Z":
            # Swap Y and Z
            points = points[:, [0, 2, 1]]
            points[:, 2] = -points[:, 2]
        
        num_points = len(points)
        degree = min(3, num_points - 1)  # Cubic or lower
        
        # Model node
        lines.extend([
            f'\tModel: {model_id}, "Model::{curve_name}", "NurbsCurve" {{',
            "\t\tVersion: 232",
            "\t\tProperties70:  {",
            "\t\t\tP: \"Lcl Translation\", \"Lcl Translation\", \"\", \"A\",0,0,0",
            "\t\t\tP: \"Lcl Rotation\", \"Lcl Rotation\", \"\", \"A\",0,0,0",
            "\t\t\tP: \"Lcl Scaling\", \"Lcl Scaling\", \"\", \"A\",1,1,1",
        ])
        
        # Add color property if enabled
        if self.options.include_color and len(strand.colors) > 0:
            avg_color = np.mean(strand.colors, axis=0)
            lines.append(f'\t\t\tP: "Color", "ColorRGB", "Color", "",{avg_color[0]:.6f},{avg_color[1]:.6f},{avg_color[2]:.6f}')
        
        lines.extend([
            "\t\t}",
            "\t\tShading: Y",
            "\t\tCulling: \"CullingOff\"",
            "\t}",
        ])
        
        # Geometry node (NURBS curve)
        lines.extend([
            f'\tGeometry: {geometry_id}, "Geometry::{curve_name}", "NurbsCurve" {{',
        ])
        
        # Control points
        lines.append(f"\t\tPoints: *{num_points * 4} {{")
        lines.append("\t\t\ta: ", )
        
        # Format control points (x, y, z, w)
        point_values = []
        for p in points:
            point_values.extend([f"{p[0]:.6f}", f"{p[1]:.6f}", f"{p[2]:.6f}", "1.000000"])
        
        # Split into lines of 8 values
        for j in range(0, len(point_values), 8):
            chunk = point_values[j:j+8]
            prefix = "\t\t\ta: " if j == 0 else "\t\t\t"
            suffix = "" if j + 8 >= len(point_values) else ","
            lines[-1] = prefix + ",".join(chunk) + suffix
            if j + 8 < len(point_values):
                lines.append("")
        
        lines.append("\t\t}")
        
        # Knot vector (open uniform)
        num_knots = num_points + degree + 1
        knots = []
        for k in range(num_knots):
            if k <= degree:
                knots.append(0.0)
            elif k >= num_knots - degree - 1:
                knots.append(1.0)
            else:
                knots.append((k - degree) / (num_points - degree))
        
        lines.append(f"\t\tKnotVector: *{num_knots} {{")
        knot_str = ",".join([f"{k:.6f}" for k in knots])
        lines.append(f"\t\t\ta: {knot_str}")
        lines.append("\t\t}")
        
        # Order and form
        lines.append(f"\t\tOrder: {degree + 1}")
        lines.append("\t\tForm: \"Open\"")
        
        lines.append("\t}")
        
        return lines
    
    def _generate_connections(self, strands: HairStrandCollection) -> List[str]:
        """Generate connections section."""
        lines = ["Connections:  {"]
        
        # Connect root to scene
        lines.append(f'\tC: "OO",{self._root_id},0')
        
        # Connect each curve model to root
        for model_id in self._curve_model_ids:
            lines.append(f'\tC: "OO",{model_id},{self._root_id}')
        
        # Connect each geometry to its model
        for model_id, geometry_id in zip(self._curve_model_ids, self._curve_geometry_ids):
            lines.append(f'\tC: "OO",{geometry_id},{model_id}')
        
        lines.append("}")
        lines.append("")
        
        return lines
    
    def _generate_takes(self) -> List[str]:
        """Generate takes section."""
        return [
            "Takes:  {",
            '\tCurrent: "Take 001"',
            '\tTake: "Take 001" {',
            "\t\tFileName: \"Take_001.tak\"",
            "\t\tLocalTime: 0,153953860000",
            "\t\tReferenceTime: 0,153953860000",
            "\t}",
            "}",
            "",
        ]


def export_strands_to_fbx(
    strands: HairStrandCollection,
    output_path: str,
    options: Optional[FBXExportOptions] = None,
    callback: Optional[callable] = None
) -> bool:
    """
    Convenience function to export strands to FBX.
    
    Args:
        strands: Hair strands to export
        output_path: Output file path
        options: Export options
        callback: Progress callback
        
    Returns:
        True if export succeeded
    """
    exporter = FBXExporter(options)
    return exporter.export(strands, output_path, callback)